### ISSUE TITLE
Unset `unset` values

### ISSUE THREAD

**Issue by piranna** [editorconfig/editorconfig-core-js#123]
According to the spec, `unset` values should be considered as the definitions are not being provided in the `.editorconfig` file (they are "unset"), but reading the code, they are just only used [as part of Typescript types](https://github.com/editorconfig/editorconfig-core-js/blob/2e87ce4a02ff395ef689a7c4e1b2fd7d4466e513/src/index.ts#L17C1-L25). Is this on purpose so they can be passed down to the code using this library, or should they be filtered out so devs don't need to check for it explicitly? I think the second one... If so, I can create a quick PR for it.

**Comment by hildjj** [comment]
I think this is likely a bug.  Will look at it.

**Comment by hildjj** [comment]
Wow.  The tests are *explicitly* wrong.

https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b296dc31124d0303895c163013450bd97958/filetree/CMakeLists.txt#L94

**Comment by hildjj** [comment]
https://github.com/editorconfig/editorconfig-core-test/issues/12

**Comment by hildjj** [comment]
OK, I can do a couple of things:
- Give an `unset()` function that goes through the resulting property object removing anything with the value "unset"
- Add an `unset` property to ParseOptions that will call `unset` automatically at the end of processing
- Add a `--unset` flag to the CLI to set that property

I don't think I can make it the default, since "plugins" are supposed to be processing "unset"'s, according to the core devs.

Reactions?

**Comment by piranna** [comment]
Si, it's intended that `unset`ed values have a values of `unset` instead of undefined, and I need to process `unset` values on my Code at application level, isn't It?

**Comment by piranna** [comment]
And yes, I've read both threads, and found that dumb :-(

**Comment by hildjj** [comment]
> And yes, I've read both threads, and found that dumb :-(

Same here.  Anyway, I'm going to land this "fix" for you, and push out 2.0.
