### ISSUE TITLE
Sync parse functions

### ISSUE THREAD

**Issue by schorfES** [editorconfig/editorconfig-core-js#26]
Since version 0.12 the ```parse```and ```parseFromFiles``` function returns a promise. This effects a lot of libraries/code which expects a sync parsing of the editorconfig file. A change to promises and to async handling would effect the API of those libraries. Can we expose also functions like ```parseSync``` and ```parseFromFilesSync```?

**Comment by treyhunner** [comment]
That sounds like a good idea.  I'm happy to code review a pull request for this.

**Comment by jedmao** [comment]
Definitely sounds like a good idea. This would also be consistent with other Node libraries. Also, I think the reason this was introduced was more of a versioning issue. We wanted the core versions to be consistent with each other, but in this case and I'm sure others, we'll need to bump the major version because it introduces breaking changes. In other words, I don't think we should be concerned at all with the version of editorconfig-core-js being the exact same as the C core. We should, however, note the version parity with other cores.

**Comment by schorfES** [comment]
Oh yeah! I didn't noticed that you already fixed this in this commit bcbe8eb6c671251cea2c5a47ded1f6557cabcefe by @seka 

Many Thanks!!!
