### ISSUE TITLE
Minimum supported node version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [editorconfig/editorconfig-core-js#40]
What is the minimum supported version of node?  Is this documented?

**Comment by jedmao** [comment]
https://github.com/editorconfig/editorconfig-core-js/blob/master/.travis.yml#L5-L7

**Comment by ahmadnassri** [comment]
should probably create a new major version and limit to > 4.x as that is now the minimum LTS

**Comment by platinumazure** [comment]
@jedmao So as it turns out, the Travis tests are now failing (in 0.10/0.12) due to the use of object shorthand in the main API file. I'm happy to write a PR to get the tests passing in those versions if you like and you could cut a new patch release; then if you want to support newer versions of node, that could be done in a minor release (if we want to keep compatibility for 0.10/0.12) or a major release (if we want to drop that compatibility).

Let me know if I can help with some PRs.

**Comment by jedmao** [comment]
@platinumazure yeah let's ditch 0.10 and 0.12 and move on over to v4 and above. PRs are appreciated.

**Comment by jedmao** [comment]
Dropped support for Node v4 in v15 of this package.
